name: prefect-ci

on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                prefect-version: [ "3.2.0" ]
        services:
            docker:
                image: docker:dind
                options: --privileged
        steps:
            -   uses: actions/checkout@v6

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v6
                with:
                    python-version: "3.12"

            -   name: update package manager & install python3 environment
                run: |
                    pip install poetry
                    poetry install --no-interaction --sync --with dev

            -   name: prefect regression process ${{ matrix.prefect-version }}
                run: poetry run alfred ci:regression --prefect ${{ matrix.prefect-version }}

            -   name: collect log on failure
                if: failure()
                uses: jwalton/gh-docker-logs@v1

            -   name: Afficher logs docker:dind en détail
                if: failure()
                run: |
                    echo "=== DOCKER:DIND DÉTAILLÉ ==="
                    docker logs --tail 500 -t ${{ job.services.docker.id }} || true
