name: publish

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-20.04

        environment:
            name: pypi

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: update package manager & install python3 environment
              run: |
                pip install poetry
                poetry install

            - name: publish on pypi
              run: poetry run alfred publish:pypi
              env:
                  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
                  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
